name: Reveal Tauri Key

on:
  workflow_dispatch:

jobs:
  reveal-key:
    runs-on: ubuntu-latest
    steps:
      - name: Output Key in Base64 with Spaces
        env:
          TAURI_KEY: ${{ secrets.TAURI_SIGNING_PRIVATE_KEY }}
        run: |
          echo "$TAURI_KEY" | base64 -w 0 | sed 's/./& /g'
          echo "" # Newline for log formatting